from typing import TypedDict, Any, Literal, get_args

Intent = Literal[
    # Full single-company financial-risk assessment.
    "company_risk_analysis",
    # Side-by-side assessment of two companies.
    "company_comparison",
    # General company profile or business overview.
    "company_overview",
    # Question about the most recent completed assessment.
    "follow_up",
    # Small talk or capability guidance.
    "chat",
    # Request outside the currently supported workflow.
    "unsupported",
]

PlannerStatus = Literal[
    # More user input is needed before any response or pipeline run.
    "collecting_inputs",
    # The state has enough inputs to run data retrieval and computations.
    "ready_for_pipeline",
    # The system must output an answer.
    "ready_for_response",
    # The request is outside the product scope or violates workflow limits.
    "unsupported",
    # User finished to perform one of the following: risk assessment, company overview or comparison between two companies
    "done",
]

SUPPORTED_INTENTS: tuple[str, ...] = get_args(Intent)
SUPPORTED_PLANNER_STATUSES: tuple[str, ...] = get_args(PlannerStatus)


class AgentState(TypedDict, total=False):
    """
    Shared LangGraph state.

    This state is passed from node to node and progressively updated.

    We use total=False because the initial workflow input will usually contain
    only user_query. Each node then adds only the fields it is responsible for.
    """

    user_query: str

    # Planner outputs
    user_query: str
    status: PlannerStatus
    intent: Intent
    tickers: list[str]
    company_names: list[str]
    start_date: str | None
    end_date: str | None
    missing_inputs: list[str]
    follow_up_questions: list[str]
    
    # Research outputs
    company_data: dict[str, dict[str, Any]]
    macro_data: dict[str, dict[str, Any]]

    # Computation outputs
    company_metrics: dict[str, dict[str, Any]]
    comparison_metrics: dict[str, Any] | None
    macro_summary: dict[str, Any] | None

    # Control / diagnostics
    errors: list[str]
    agents_passed: list[str]
    intents_passed: list[str]
    llm_usage_by_agent: dict[str, dict[str, int | float]]
    prompt_tokens: int
    output_tokens: int
    total_tokens: int
    context_window_tokens: int
    context_memory_pct: float
    
    # Current call token counters (reset per agent invocation)
    planner_prompt_tokens: int
    planner_output_tokens: int
    planner_total_tokens: int
    planner_token_limit: int
    messenger_prompt_tokens: int
    messenger_output_tokens: int
    messenger_total_tokens: int
    messenger_token_limit: int

    # Writer input/output or chat/follow up response
    answer: str | None

    # Follow up question response or last report generated by the system
    last_report: str | None
    last_metrics: dict[str, Any] | None
